import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { MainHeader } from './components/MainHeader';  // keep if your components live under app/components
import { MainFooter } from './components/MainFooter';
// If your components are in src/components, switch to:
// import { MainHeader } from '@/components/MainHeader';
// import { MainFooter } from '@/components/MainFooter';

import QueryProvider from '@/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <QueryProvider>
          <MainHeader />
          <main className="flex-1">
            {children}
          </main>
          <MainFooter />
        </QueryProvider>
      </body>
    </html>
  );
}
